var debugObject,showPathFlag=!1,currentSpatialObjects={},selectedSpatialObject,websocket=new WebSocket("ws://localhost:9764/outputwebsocket/DefaultWebsocketOutputAdaptor/geoDataEndPoint");websocket.onopen=function(){$.UIkit.notify({message:"You Are Connectedto Map Server!!",status:"warning",timeout:1E3,pos:"bottom-left"})};
websocket.onmessage=function(a){a=$.parseJSON(a.data);a.id in currentSpatialObjects?currentSpatialObjects[a.id].update(a):(a=new SpatialObject(a),currentSpatialObjects[a.id]=a,currentSpatialObjects[a.id].addTo(map))};
var normalIcon=L.icon({iconUrl:"assets/img/markers/arrow_normal.png",shadowUrl:!1,iconSize:[24,24],iconAnchor:[12,12],popupAnchor:[-2,-5]}),alertedIcon=L.icon({iconUrl:"assets/img/markers/arrow_alerted.png",shadowUrl:!1,iconSize:[24,24],iconAnchor:[12,12],popupAnchor:[-2,-5]}),offlineIcon=L.icon({iconUrl:"assets/img/markers/arrow_offline.png",iconSize:[24,24],iconAnchor:[12,12],popupAnchor:[-2,-5]}),defaultIcon=L.icon({iconUrl:"assets/img/markers/default_icons/marker-icon.png",iconSize:[24,24],iconAnchor:[12,
12],popupAnchor:[-2,-5]});
function SpatialObject(a){this.id=a.id;this.pathGeoJsons=[];this.path=[];var c=function(a,b,c){return{type:"Feature",properties:{state:a,information:b},geometry:{type:"LineString",coordinates:[c]}}};this.speedHistory=["speed"];this.geoJson=L.geoJson(a,{pointToLayer:function(a,b){return L.marker(b,{icon:normalIcon,iconAngle:this.heading})}});this.marker=this.geoJson.getLayers()[0];this.marker.options.title=this.id;this.popupTemplate=$("#markerPopup");this.marker.bindPopup(this.popupTemplate.html());this.addTo=
function(a){this.geoJson.addTo(a)};this.setSpeed=function(a){this.speed=a;this.speedHistory.push(a);20<this.speedHistory.length&&this.speedHistory.splice(1,1)};this.stateIcon=function(){switch(this.state){case "NORMAL":return normalIcon;case "ALERTED":return alertedIcon;case "OFFLINE":return offlineIcon;default:return defaultIcon}};this.updatePath=function(a){this.path[this.path.length-1].addLatLng(a)};this.drawPath=function(){var a=[];0<this.path.length&&this.removePath();for(var b in this.pathGeoJsons){var c=
new L.polyline(this.pathGeoJsons[b].geometry.coordinates,d(this.pathGeoJsons[b].properties.state)),g=this.pathGeoJsons[b].geometry.coordinates[0];console.log("DEBUG: previousSectionLastPoint = "+a+" currentSectionFirstPoint = "+g);a.push(g);g=new L.polyline(a,d());a=[this.pathGeoJsons[b].geometry.coordinates[this.pathGeoJsons[b].geometry.coordinates.length-1]];g.addTo(map);this.path.push(g);console.log("DEBUG: Alert Information: "+this.pathGeoJsons[b].properties.information);c.bindPopup("Alert Information: "+
this.pathGeoJsons[b].properties.information);c.addTo(map);this.path.push(c)}};this.removePath=function(){for(var a in this.path)map.removeLayer(this.path[a]);this.path=[]};var b,d=function(a){switch(a){case "NORMAL":b="blue";break;case "ALERTED":b="red";break;case "WARNING":b="orange";break;case "OFFLINE":b="green";break;default:return{color:"#19FFFF",weight:8}}return{color:b,weight:8}};this.update=function(a){this.latitude=a.geometry.coordinates[1];this.longitude=a.geometry.coordinates[0];this.setSpeed(a.properties.speed);
this.state=a.properties.state;this.heading=a.properties.heading;this.information=a.properties.information;if(a.properties.notify){"NORMAL"!=this.state&&notifyAlert("Object ID: <span style='color: blue;cursor: pointer' onclick='focusOnSpatialObject("+this.id+")'>"+this.id+"</span> change state to: <span style='color: red'>"+a.properties.state+"</span> Info : "+a.properties.information);var b=c(this.state,this.information,[this.latitude,this.longitude]);this.pathGeoJsons.push(b);if(selectedSpatialObject==
this.id){var h=new L.polyline(b.geometry.coordinates,d(a.properties.state));h.bindPopup("Alert Information: "+b.properties.information);b=this.path[this.path.length-1].getLatLngs();b=new L.polyline([b[b.length-1],[this.latitude,this.longitude]],d());this.path.push(b);this.path.push(h);b.addTo(map);h.addTo(map)}}this.marker.setLatLng([this.latitude,this.longitude]);this.marker.setIconAngle(this.heading);this.marker.setIcon(this.stateIcon());try{this.pathGeoJsons[this.pathGeoJsons.length-1].geometry.coordinates.push([a.geometry.coordinates[1],
a.geometry.coordinates[0]])}catch(g){console.log("DEBUG: Dam error = "+g),b=c(this.state,this.information,[a.geometry.coordinates[1],a.geometry.coordinates[0]]),this.pathGeoJsons.push(b)}selectedSpatialObject==this.id&&(this.updatePath([a.geometry.coordinates[1],a.geometry.coordinates[0]]),chart.load({columns:[this.speedHistory]}),map.setView([this.latitude,this.longitude]));this.popupTemplate.find("#objectId").html(this.id);this.popupTemplate.find("#information").html(this.information);this.popupTemplate.find("#speed").html(this.speed);
this.popupTemplate.find("#heading").html(this.heading);this.marker.setPopupContent(this.popupTemplate.html())};this.update(a);return this}function notifyAlert(a){$.UIkit.notify({message:"Alert: "+a,status:"warning",timeout:3E3,pos:"bottom-left"})}function Alert(a,c,b){this.type=a;this.message=c;this.level=b?b:"info";this.notify=function(){$.UIkit.notify({message:this.level+": "+this.type+" "+this.message,status:"info",timeout:1E3,pos:"bottom-left"})}};function addTileUrl(){tileUrl=$("#tileUrl").val();urlName=$("#tileName").val();maxzoom=$("#maxzoom").val();subdomains=$("#sub_domains").val();attribution=$("#data_attribution").val();var a=L.tileLayer(tileUrl,{maxZoom:parseInt(maxzoom),subdomains:subdomains.split(","),attribution:attribution});layerControl.addBaseLayer(a,urlName);inputs=layerControl._form.getElementsByTagName("input");inputsLen=inputs.length;for(i=0;i<inputsLen;i++)input=inputs[i],obj=layerControl._layers[input.layerId],layerControl._map.hasLayer(obj.layer)&&
map.removeLayer(obj.layer);map.addLayer(a);$.post("controllers/tile_servers.jag",{url:tileUrl,name:urlName,attribution:attribution,maxzoom:maxzoom,subdomains:subdomains},function(a){$.UIkit.notify({message:'<span style="color: dodgerblue">'+a+"</span>",status:"success",timeout:3E3,pos:"top-center"});closeAll()})}
var defaultOSM=L.tileLayer("http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'Map data \u00a9 OpenStreetMap contributors <a href="http://openstreetmap.org/" target="_blank">Openstreetmap</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png">. Map data (c) <a href="http://www.openstreetmap.org/" target="_blank">OpenStreetMap</a> contributors, CC-BY-SA.'}),baseLayers={"Open Street Maps":defaultOSM};
function getTileServers(){$.getJSON("controllers/tile_servers.jag?serverId=all",function(a){$.each(a,function(a,b){$.UIkit.notify({message:'Loading... <span style="color: #ccfcff">'+b.name+'</span> URL: <span style="color: #00ff00">'+b.url+"</span>",status:"info",timeout:2E3,pos:"bottom-left"});var d=L.tileLayer(b.url,{maxZoom:b.maxzoom,subdomains:b.subdomains.split(","),attribution:b.attribution});layerControl.addBaseLayer(d,b.name)})})}
function addWmsEndPoint(){serviceName=$("#serviceName").val();layers=$("#layers").val();wmsVersion=$("#wmsVersion").val();serviceEndPoint=$("#serviceEndPoint").val();outputFormat=$("#outputFormat").val();wmsLayer=L.tileLayer.wms(serviceEndPoint,{layers:layers.split(","),format:outputFormat?outputFormat:"image/png",transparent:!0,opacity:.4});layerControl.addOverlay(wmsLayer,serviceName,"Web Map Service layers");map.addLayer(wmsLayer);$.post("controllers/wms_endpoints.jag",{serviceName:serviceName,
layers:layers,wmsVersion:wmsVersion,serviceEndPoint:serviceEndPoint,outputFormat:outputFormat},function(a){$.UIkit.notify({message:'<span style="color: dodgerblue">'+a+"</span>",status:"success",timeout:3E3,pos:"top-center"});closeAll()})}
function getWms(){$.getJSON("controllers/wms_endpoints.jag?serverId=all",function(a){$.each(a,function(a,b){wmsLayer=L.tileLayer.wms(b.serviceUrl,{layers:b.layers.split(","),format:b.format?b.format:"image/png",version:b.version,transparent:!0,opacity:.4});layerControl.addOverlay(wmsLayer,b.name,"Web Map Service layers")})})}
function setSpeedAlert(){var a=$("#speedAlertValue").val();data={parseData:JSON.stringify({speedAlertValue:a}),executionPlan:"speed",customName:null,cepAction:"edit"};$.post("controllers/set_alerts.jag",data,function(a){$.UIkit.notify({message:'<span style="color: dodgerblue">'+a.status+"</span><br>"+a.message,status:"success"==a.status?"success":"danger",timeout:3E3,pos:"top-center"});closeAll()},"json")}
function setWithinAlert(a){var c=JSON.stringify(map._layers[a].toGeoJSON().geometry).replace(/"/g,"'"),b=$("#queryName").val(),d=$("#areaName").val();data={parseData:JSON.stringify({geoFenceGeoJSON:c,executionPlanName:createExecutionPlanName(b),areaName:d}),executionPlan:"within",customName:d,queryName:b,cepAction:"deploy"};$.post("controllers/set_alerts.jag",data,function(b){$.UIkit.notify({message:'<span style="color: dodgerblue">'+b.status+"</span><br>"+b.message,status:"success"==b.status?"success":
"danger",timeout:3E3,pos:"top-center"});closeAll();closeWithinTools(a)},"json")}function removeGeoFence(a){var c=$(a).attr("data-queryName");$(a).attr("data-areaName");data={executionPlanName:createExecutionPlanName(c),queryName:c,cepAction:"undeploy"};$.post("controllers/remove_alerts.jag",data,function(a){$.UIkit.notify({message:'<span style="color: dodgerblue">'+a.status+"</span><br>"+a.message,status:"success"==a.status?"success":"danger",timeout:3E3,pos:"top-center"});closeAll()},"json")}
function getAlertsHistory(a){$.getJSON("controllers/get_alerts_history.jag?objectId="+a,function(a){var b=$("#showAlertsArea").empty();$.each(a,function(a,c){var e=document.createElement("a");switch(c.state){case "NORMAL":return;case "WARNING":$(e).addClass("list-group-item list-group-item-warning");break;case "ALERTED":$(e).addClass("list-group-item list-group-item-danger");break;case "OFFLINE":$(e).addClass("list-group-item list-group-item-success")}$(e).html(c.information);$(e).css({marginTop:"5px"});
$(e).attr("onClick","showAlertInMap(this)");$(e).attr("data-id",c.id);$(e).attr("data-latitude",c.latitude);$(e).attr("data-longitude",c.longitude);$(e).attr("data-state",c.state);$(e).attr("data-information",c.information);b.append(e)})})}function createExecutionPlanName(a){return"geo_within"+(a?"_"+a:"")+"_alert"}function closeAll(){$(".modal").modal("hide");setTimeout(function(){$.UIkit.offcanvas.hide()},100)};var drawControl;
function openWithinTools(){closeAll();$.UIkit.notify({message:"Please draw the required area on the map",status:"success",timeout:3E3,pos:"top-center"});L.Control.RemoveAll=L.Control.extend({options:{position:"topleft"},onAdd:function(a){var d=L.DomUtil.create("div","leaflet-draw-toolbar leaflet-bar");L.DomEvent.addListener(d,"click",L.DomEvent.stopPropagation).addListener(d,"click",L.DomEvent.preventDefault).addListener(d,"click",function(){d.remove();drawControl.removeFrom(a);c.clearLayers()});var f=
L.DomUtil.create("a","fa fa-times fa-lg drawControlCloseButton",d);$(f).css("background-image","none");$(f).mouseenter(function(){$(this).css("color","red")}).mouseleave(function(){$(this).css("color","black")});f.title="Close drawer tools";f.href="#";return d}});var a=new L.Control.RemoveAll;map.addControl(a);var c=new L.FeatureGroup;map.addLayer(c);L.Icon.extend({options:{shadowUrl:"assets/img/markers/default_icons/marker-shadow.png",iconUrl:"assets/img/markers/default_icons/marker-icon.png"}});
drawControl=new L.Control.Draw({draw:{polygon:{allowIntersection:!1,drawError:{color:"#e1e100",message:"<strong>Oh snap!<strong> you can't draw that!"},shapeOptions:{color:"#ff0043"}},rectangle:{shapeOptions:{color:"#002bff"}},polyline:!1,circle:!1,marker:!1},edit:{featureGroup:c}});map.addControl(drawControl);map.on("draw:created",function(a){a=a.layer;c.addLayer(a);createPopup(a)})}
function createPopup(a){var c=$("#setWithinAlert");c.find("#exportGeoJson").attr("leaflet_id",a._leaflet_id);c.find("#editGeoJson").attr("leaflet_id",a._leaflet_id);c.find("#addWithinAlert").attr("leaflet_id",a._leaflet_id);a.bindPopup(c.html(),{closeOnClick:!1,closeButton:!1}).openPopup();$(a._popup._container.childNodes[0]).css("background","rgba(255,255,255,0.8)")}
function closeWithinTools(a){map.removeLayer(map._layers[a]);map.removeControl(drawControl);console.log("DEBUG: closeWithinTools(leafletId) = "+a)}function exportToGeoJSON(a,c){var b="data:application/json;charset=utf-8,"+encodeURIComponent(c),d=$(a).closest("form").find("#areaName").val()||"geoJson";$(a).attr({href:b,target:"_blank",download:d+".json"})}$(function(){$("#importGeoJsonFile").change(function(){var a=this.files[0],c=new FileReader;c.readAsText(a);c.onload=function(a){$("#enterGeoJson").text(a.target.result.toString())}})});
function importGeoJson(){var a;a=$("#enterGeoJson").val();updateDrawing(a)}function updateDrawing(a){a=JSON.parse(a);a.geometry.coordinates[0].pop();var c=[];$.each(a.geometry.coordinates[0],function(a,d){c.push({lat:d[1],lng:d[0]})});a=new L.Polygon(c);a.editing.enable();map.addLayer(a);createPopup(a);closeAll()}
function viewFence(a){var c=JSON.parse($(a).attr("data-geoJson")),b=$(a).attr("data-queryName"),d=$(a).attr("data-areaName");c.coordinates[0].pop();var f=[];$.each(c.coordinates[0],function(a,b){f.push({lat:b[1],lng:b[0]})});var e=new L.Polygon(f);map.addLayer(e);$("#templateLoader").load("assets/html_templates/view_fence_popup.html #viewWithinAlert",function(){var a=$("#templateLoader").find("#viewWithinAlert");a.find("#exportGeoJson").attr("leaflet_id",e._leaflet_id);a.find("#hideViewFence").attr("leaflet_id",
e._leaflet_id);a.find("#viewAreaName").html(d);a.find("#viewQueryName").html(b);e.bindPopup(a.html(),{closeButton:!1}).openPopup();$(e._popup._container.childNodes[0]).css("background","rgba(255,255,255,0.8)");closeAll()})};function showAlertInMap(a){var c=$(a).attr("data-id"),b=$(a).attr("data-latitude"),d=$(a).attr("data-longitude"),f=$(a).attr("data-state");a=$(a).attr("data-information");var b=L.latLng(b,d),e=L.circle(b,10,{color:"#FF9900",fillColor:"#FF00FF",fillOpacity:.5}).addTo(map);e.bindPopup("Id: <b>"+c+"</b><br>State: <b>"+f+"</b><br>Information: <b>"+a+"</b><br>").openPopup();$(e._popup._closeButton).on("click",function(){map.removeLayer(e)});map.setView(b,18);clearFocus()};
